# -*- coding: utf-8 -*-
"""CleanData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRIYpUPplR5Lzr1pOHmV0TeYqs6pxsxW

# Regrex
"""

import re

text = "The quick brown fox jumps over the lazy dog. The quick brown fox."
pattern = "fox"

# Using re.search()
search_match = re.search(pattern, text)
if search_match:
    print("re.search() found:", search_match.group())
else:
    print("re.search() did not find a match.")

# Using re.findall()
findall_matches = re.findall(pattern, text)
print("re.findall() found:", findall_matches)

# Using re.finditer()
print("re.finditer() found:")
for match in re.finditer(pattern, text):
    print(f"  Match: {match.group()}, Start: {match.start()}, End: {match.end()}")

import re

text_vietnamese = "Đây là ví dụ với chữ đ và Đ."
pattern_vietnamese = "[đĐ]"

found_matches = re.findall(pattern_vietnamese, text_vietnamese)

print(f"Text: {text_vietnamese}")
print(f"Pattern: {pattern_vietnamese}")
print(f"Matches found: {found_matches}")

import re

text = 'asdhjahd            asjdjad'
patern = r'\s+'
re.sub (patern,' ',text)

import re

text = """
asda




as
da
sd

    as
"""
pattern = r'\s+'

re.sub(pattern," ", text).strip()

import re
string = "Email lien he: ducanhmac113@gmail.com"
patern = r"\w+@\w+\.\w+"
re.sub(patern,"[Nhập email của bạn]",string)

"""# Tokenizers

"""

!pip install torchtext --upgrade

!pip uninstall torch torchtext -y

import torchtext
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator

# 1. Khởi tạo tokenizer
tokenizer = get_tokenizer('basic_english')

# 2. Dữ liệu câu đầu vào
sentences = [
 'I love Vietnam',
 'Vietnamese people are pretty friendly',
 'My mom loves cooking',
 'I am Vietnamese'
]

# 3. Định nghĩa các token đặc biệt
unk_token = '<unk>'  # Token không có (unknown)
pad_token = '<pad>'  # Token để padding (đệm)
bos_token = '<bos>'  # Token bắt đầu câu (begin of sentence)
eos_token = '<eos>'  # Token kết thúc câu (end of sentence)

# 4. Xây dựng từ điển (vocab)
# Nó sẽ tách các câu (sentences) bằng tokenizer, sau đó build vocab
vocab = build_vocab_from_iterator(map(tokenizer, sentences),
                                  specials=[unk_token, pad_token, bos_token, eos_token])

# 5. Đặt token mặc định
# Bất cứ từ nào không có trong vocab sẽ được gán token <unk>
vocab.set_default_index(vocab[unk_token])

# Bạn có thể thêm dòng này để xem kết quả vocab
print(vocab.get_stoi())

"""BPE vs WordPiece Tokenization

# Text Normalization
-Lemmatization (xác định từ gốc)
"""

import nltk
nltk.download('wordnet')
nltk.download('omw-1.4') # Cần thiết cho WordNet

from nltk.stem import WordNetLemmatizer

# Create WordNetLemmatizer object
wnl = WordNetLemmatizer()

# single word lemmatization examples
list1 = ['kites', 'babies', 'dogs', 'flying', 'smiling',
         'driving', 'died', 'tried', 'feet']

for word in list1:
    # Thêm word + " ---> " để giống hệt output trong ảnh
    print(word + " ---> " + wnl.lemmatize(word))

nltk.download('punkt')
# phục vụ tách văn bản thành các câu , chi tiết hơn là xác đính dấu . đanh xác định có phải là . hết câu không

import nltk
from nltk.tokenize import sent_tokenize

# Đảm bảo bạn đã tải 'punkt'
# nltk.download('punkt')
nltk.download('punkt_tab')


text = "Hello Mr. Stark. Today is a good day! The price is 2.5$."

# 1. Cách sai (Dùng .split)
print("--- Tách sai (dùng split) ---")
print(text.split('.'))

# 2. Cách đúng (Dùng mô hình 'punkt')
print("\n--- Tách đúng (dùng sent_tokenize) ---")
print(sent_tokenize(text))

# Tải file dataset
!wget https://storage.googleapis.com/protonx-cloud-storage/datasets/IMDB%20Dataset.csv

import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional
from sklearn.model_selection import train_test_split

# Tải các gói cần thiết của NLTK
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('punkt_tab')

# 1. Đọc dữ liệu
df = pd.read_csv('IMDB Dataset.csv')

# 2. Định nghĩa các hàm tiền xử lý
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

# HÀM 1: Có Lemmatization
def preprocess_text(text):
    # Tách từ
    tokens = nltk.word_tokenize(text)
    # Lemmatize và lọc stop words
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens if token not in stop_words]
    # Ghép lại thành chuỗi
    return ' '.join(lemmatized_tokens)

# HÀM 2: Không có Lemmatization
def preprocess_text_no_lemmatization(text):
    # Tách từ
    tokens = nltk.word_tokenize(text)
    # Chỉ lọc stop words
    clean_tokens = [token for token in tokens if token not in stop_words]
    # Ghép lại thành chuỗi
    return ' '.join(clean_tokens)

# 3. Áp dụng các hàm
print("Đang áp dụng preprocess_text (có lemma)...")
df['processed_review_with_lemmatization'] = df['review'].apply(preprocess_text)

print("Đang áp dụng preprocess_text_no_lemmatization (không lemma)...")
df['processed_review_no_lemmatization'] = df['review'].apply(preprocess_text_no_lemmatization)

print("Hoàn thành tiền xử lý!")

df.head()

# --- Thử nghiệm Mô hình sử dụng Lemmatization ---

# 1. Chuẩn bị X và y
# Lấy dữ liệu đã được lemmatize
X = df['processed_review_with_lemmatization']
# Chuyển 'positive'/'negative' thành 1/0
y = df['sentiment'].apply(lambda x: 1 if x == 'positive' else 0)

# 2. Chia tập train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Tokenize văn bản (dùng Tokenizer của Keras)
# Kích thước từ vựng là 5000 (như trong ảnh)
tokenizer = Tokenizer(num_words=5000, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train)

# 4. Chuyển văn bản thành chuỗi số (sequences)
sequences_train = tokenizer.texts_to_sequences(X_train)
sequences_test = tokenizer.texts_to_sequences(X_test)

# 5. Pad (Đệm) các sequences cho bằng nhau (dài 200)
padded_train = pad_sequences(sequences_train, maxlen=200, truncating='post', padding='post')
padded_test = pad_sequences(sequences_test, maxlen=200, truncating='post', padding='post')

# 6. Định nghĩa mô hình (Define the model)
model_with_lemma = Sequential([
    Embedding(input_dim=5000, output_dim=16, input_length=200),
    Bidirectional(LSTM(64)),
    Dense(24, activation='relu'),
    Dense(1, activation='sigmoid')
])

# 7. Biên dịch mô hình (Compile the model)
model_with_lemma.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# 8. Huấn luyện mô hình (Train the model)
print("\n--- Bắt đầu huấn luyện mô hình (với Lemmatization) ---")
model_with_lemma.fit(padded_train, y_train, epochs=10, validation_data=(padded_test, y_test))

# 9. Đánh giá mô hình (Evaluate the model)
print("\n--- Đánh giá kết quả ---")
loss, accuracy = model_with_lemma.evaluate(padded_test, y_test)
print(f'Loss: {loss}, Accuracy: {accuracy}')

"""# Stop word Filtering
- Tốt cho bài phân loại

# Sentence Segmentation
-Tách câu

# Word Correction
- Dựa vào Jcard distance dể tìm min distance input =>
- Edit distance

# Note
- Spacy cho tiếng việt
- underthesea
- lưu ý bài toán Tiếng việt(1 từ tiếng Anh = nhiều âm tiết tiếng việt ngăn cách nhau bởi khoảng trắng)
"""

!pip install pyvi
from spacy.lang.vi import Vietnamese